apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-argo
  labels:
    app: test-argo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-argo
  template:
    metadata:
      labels:
        app: test-argo
    spec:
      containers:
      - name: test-argo
        image: nginx
        ports:
        - containerPort: 8080 #상의
